name: Publish Package

on:
  push:
    tags: 
      - "v*"

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: 
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install --upgrade pip toml maturin --user

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
  
      - name: Update version in pyproject.toml
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          python <<EOF
          import toml
          import os

          version = os.getenv("VERSION")

          with open("pyproject.toml", "r") as f:
              data = toml.load(f)

          data["project"]["version"] = version

          with open("pyproject.toml", "w") as f:
              toml.dump(data, f)
          EOF
          
      - name: Build binary wheel and source tarball with maturin
        run: |
          maturin build --features python --release

      - name: Store distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: target/wheels/*
